apiVersion: v1
kind: Service
metadata:
  name: kotlin-spring
  labels:
    app: kotlin-spring
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 8080
  selector:
    app: kotlin-spring
