apiVersion: v1
kind: Service
metadata:
  name: node-express
  labels:
    app: node-express
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: node-express
